# Generated by Django 4.1.2 on 2022-10-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QuizeQuestions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(default=None, max_length=254)),
                ('op1', models.CharField(default=None, max_length=100)),
                ('op2', models.CharField(default=None, max_length=100)),
                ('op3', models.CharField(default=None, max_length=100)),
                ('op4', models.CharField(default=None, max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default=None, max_length=30)),
                ('last_name', models.CharField(blank=True, default=None, max_length=30, null=True)),
                ('email', models.EmailField(default=None, max_length=100)),
                ('password', models.CharField(default=None, max_length=255)),
            ],
        ),
    ]
