# Generated by Django 4.1.2 on 2022-10-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizequestions',
            name='question',
            field=models.CharField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userdata',
            name='email',
            field=models.EmailField(default=None, max_length=100, unique=True),
        ),
    ]
