# Generated by Django 4.1.2 on 2022-10-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0003_alter_userdata_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quizequestions',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
