# Generated by Django 4.1.2 on 2022-10-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0004_alter_quizequestions_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizequestions',
            name='ans',
            field=models.CharField(default=None, max_length=100),
        ),
    ]
