# Generated by Django 4.1.2 on 2022-10-17 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0005_quizequestions_ans'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.CharField(default=0, max_length=4)),
                ('player', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='QuizApp.userdata')),
            ],
        ),
    ]
