# Generated by Django 4.1.2 on 2022-10-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0006_leaderboard'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leaderboard',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
