# Generated by Django 4.1 on 2022-10-21 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QuizApp', '0007_alter_leaderboard_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdata',
            name='correct',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='userdata',
            name='score',
            field=models.CharField(default=0, max_length=30),
        ),
        migrations.AddField(
            model_name='userdata',
            name='wrong',
            field=models.CharField(blank=True, default=0, max_length=30, null=True),
        ),
    ]
